In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import numpy as np

# create a list

In [12]:
scores=[10,20,30,40,50,60,77,23]

In [54]:
scores+2

TypeError: can only concatenate list (not "int") to list

In [ ]:
scores[0]+2

In [ ]:
for i in scores:
    i+2
    scores.append(1)


In [13]:
arr=np.array([77,82,49,56,35,33,99])

In [14]:
arr

array([77, 82, 49, 56, 35, 33, 99])

In [15]:
arr+3

array([ 80,  85,  52,  59,  38,  36, 102])

# List is Heteregenous and Arrays are Homogenous


In [16]:
scores=([44,76,82])

In [17]:
scores

[44, 76, 82]

In [18]:
scores_1=([44.5,76,82])

In [59]:
scores_1

[44.5, 76, 82]

In [60]:
arr=np.array([44,76,82])

In [61]:
arr

array([44, 76, 82])

In [62]:
arr_1=np.array([44.5,76,82])

In [20]:
arr_1

[44.5, 76, 82]

In [78]:
arr_2

NameError: name 'arr_2' is not defined

# Create 1D array

In [22]:
arr_1=np.array([1,2,3,4,5,6,7,8])

In [23]:
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
arr_1.ndim

1

# create 2D array

In [38]:
arr_2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [39]:
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
arr_2.ndim

2

# create 3D array

In [41]:
arr_3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [42]:
arr_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [43]:
arr_3.ndim

3

# create 4D array

In [74]:
arr_4=np.array([[1,2,3],[4,5,6],[7,8,9],[10.5,11,12]])

In [75]:
arr_4

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [10.5, 11. , 12. ]])

In [76]:
arr_4.ndim

2

In [77]:
arr_4

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [10.5, 11. , 12. ]])

In [78]:
arr_4[2][1]=np.nan

In [84]:
arr_4

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., nan,  9.],
       [nan, nan, nan]])

In [85]:
arr_4[3]=np.nan

In [86]:
arr_4

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., nan,  9.],
       [nan, nan, nan]])

#

In [103]:
arr_5=np.array([3,5,7,8,9,2,6,4,50])

In [104]:
arr_5

array([ 3,  5,  7,  8,  9,  2,  6,  4, 50])

In [105]:
arr_5.mean()

np.float64(10.444444444444445)

In [106]:
arr_5.max()

np.int64(50)

In [107]:
arr_5.min()

np.int64(2)

In [108]:
arr_5.std()

np.float64(14.150862644384862)

In [109]:
arr_5.sort()

In [110]:
arr_5

array([ 2,  3,  4,  5,  6,  7,  8,  9, 50])

In [111]:
arr_5.argmax()

np.int64(8)

In [112]:
arr_5.cumsum()

array([ 2,  5,  9, 14, 20, 27, 35, 44, 94])

In [ ]:
##

In [ ]:
arr_5.

In [113]:
arr_3.ndim

3

In [123]:
arr_6=arr_3.flatten()

In [124]:
arr_6.ndim

1

### 

In [129]:
np.linspace(1,25,50)

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [131]:
 1.48979592-1

0.48979591999999994

In [132]:
1.48979592-1.97959184

-0.48979592000000016

In [133]:
np.arange(1,10,15)

array([1])

In [136]:
np.random.rand(2,30)

array([[0.05607242, 0.21189208, 0.64377976, 0.43143299, 0.68965969,
        0.12822366, 0.17640723, 0.69961892, 0.70038262, 0.75121739,
        0.45343005, 0.7253266 , 0.87384571, 0.72522831, 0.38627651,
        0.62027717, 0.87677775, 0.10525315, 0.13338352, 0.98131718,
        0.31735522, 0.26221922, 0.76941273, 0.54310735, 0.85386436,
        0.39514082, 0.83585053, 0.35863495, 0.11265973, 0.78382136],
       [0.20523234, 0.14496704, 0.75807242, 0.7138487 , 0.0029394 ,
        0.41319165, 0.32824944, 0.31720767, 0.71759672, 0.11150102,
        0.74190882, 0.21335258, 0.51987221, 0.7971565 , 0.30409914,
        0.24654691, 0.75665914, 0.92644534, 0.9853148 , 0.87005172,
        0.11447209, 0.86525793, 0.32535877, 0.78030854, 0.8399853 ,
        0.59573266, 0.11310199, 0.75709016, 0.66768247, 0.56232437]])

In [137]:
np.random.seed(20)
np.random.rand(2,30)

array([[0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959,
        0.69175758, 0.37868094, 0.51851095, 0.65795147, 0.19385022,
        0.2723164 , 0.71860593, 0.78300361, 0.85032764, 0.77524489,
        0.03666431, 0.11669374, 0.7512807 , 0.23921822, 0.25480601,
        0.85762553, 0.94977903, 0.56168686, 0.17878052, 0.77025193,
        0.49238104, 0.63125307, 0.83949792, 0.4610394 , 0.49794007],
       [0.67941112, 0.65078591, 0.26879524, 0.06732467, 0.77144514,
        0.48098413, 0.32920641, 0.51064106, 0.26362883, 0.31051155,
        0.62685344, 0.55744981, 0.31857956, 0.39484322, 0.25797459,
        0.58224112, 0.16162871, 0.59813382, 0.82582358, 0.15639172,
        0.73430052, 0.40864343, 0.7786879 , 0.80397057, 0.78607144,
        0.59228702, 0.6644892 , 0.64656729, 0.42563648, 0.51356833]])

In [138]:
np.random.randint(1,90,50)

array([11, 39, 10, 61, 61, 24, 53, 77, 79, 55, 82, 74, 28, 40, 88, 10, 15,
       32, 57, 57, 59, 80, 28, 51, 75, 70,  3, 58, 24, 26, 42, 10, 67, 16,
       66, 31, 89, 50, 41, 12, 70,  1, 59, 87, 38, 69, 19, 10, 58, 15],
      dtype=int32)

In [139]:
np.random.randn(2,10)

array([[ 0.14362263,  0.75029793, -0.40957143,  1.44740705, -0.40453402,
         1.14892501, -0.93891049, -1.90146405,  1.09543335, -0.33354379],
       [-1.44184857, -1.41666675, -1.62950152, -1.81525581, -1.056169  ,
         0.55427493, -0.95001801,  0.85799935, -0.53207925,  1.12575886]])